version: "3.9"

services:
  web:
    container_name: web
    build:
      context: ./website
      dockerfile: ./Dockerfile
    image: web:latest
    networks:
      - aisb
    restart: on-failure:5
    env_file: ./website/.env.local
    depends_on:
      - chroma
      - database
  reverse-proxy:
    container_name: proxy
    image: nginx:1.25.3
    networks:
      - aisb
    restart: on-failure:5
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/web-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/cert.pem:/etc/cf/cert.pem:ro
      - ./config/key.pem:/etc/cf/key.pem:ro
      # https://developers.cloudflare.com/ssl/origin-configuration/authenticated-origin-pull/set-up/zone-level/#:~:text=download%20the%20.PEM%20file
      - ./config/cc-cert.pem:/etc/cf/cc-cert.pem:ro
    depends_on:
      - web
  chroma:
    container_name: vectorstore
    image: ghcr.io/chroma-core/chroma:latest
    networks:
      - aisb
    restart: on-failure:5
    volumes:
      - chroma_vol:/chroma
    ports:
      - 8000:8000
  database:
    container_name: database
    image: postgres:alpine
    networks:
      - aisb
    ports:
      - 5432:5432
    restart: on-failure:5
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    volumes:
      - "database_data:/var/lib/postgresql/data"

networks:
  aisb:

volumes:
  chroma_vol:
  database_data:
