version: "3.9"

services:
  reverse-proxy:
    container_name: proxy
    network_mode: host
    image: nginx:1.25.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./aistudybuddy.se.pem:/etc/cf/aistudybuddy.se.pem:ro
      - ./private.pem:/etc/cf/private.pem:ro
  chroma:
    container_name: vectorstore
    network_mode: host
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_vol:/chroma
    ports:
      - 8000:8000
  database:
    container_name: database
    network_mode: host
    image: postgres:alpine
    ports:
      - 5432:5432
    restart: on-failure:5
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    volumes:
      - "database_data:/var/lib/postgresql/data"

volumes:
  chroma_vol:
  database_data:
