version: "3.9"

services:
  llm:
    container_name: llm
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: llm:latest
    ports:
      - 3030:3030
    networks:
      - aisb
    volumes:
      - /home/jonathan/Downloads/zephyr-7b-beta.Q6_K.gguf:/var/data/llm.gguf:ro
    # runtime: nvidia
    # command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities: [gpu, compute]
  reverse-proxy:
    container_name: proxy
    image: nginx:1.25.3
    networks:
      - aisb
    restart: on-failure:5
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/gpu-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/cert.pem:/etc/cf/cert.pem:ro
      - ./config/key.pem:/etc/cf/key.pem:ro

networks:
  aisb:
