app = "aisb-web"
primary_region = "arn"

[deploy]
    strategy = "immediate"

[build]
    ignorefile = "./.dockerignore"
    dockerfile = "./Dockerfile"

[env]
    HOSTNAME = "0.0.0.0"
    PORT = "3000"
    COOKIE_DOMAIN = "aistudybuddy.se"
    NEXTAUTH_URL = "https://aistudybuddy.se"

[http_service]
    internal_port = 3000
    force_https = true
    auto_stop_machines = false
    auto_start_machines = true
    min_machines_running = 1
    [http_service.concurrency]
        type = "requests"
        hard_limit = 100
        soft_limit = 50
    [[http_service.checks]]
        grace_period = "10s"
        interval = "5s"
        method = "GET"
        timeout = "3s"
        path = "/api/healthcheck"